ENV_RUNNING_TIME = 10000
SCREEN_LENGTH = 450
SCREEN_HEIGHT = 450

REPORT_INTERVAL = 5
NUM_OF_HARES = 8
NUM_OF_WOLVES = 5

ANIMAL_START_ENERGY = 1000
ANIMAL_MAX_SPEED_DEFAULT = 12
ANIMAL_EATING_DURATION_DEFAULT = 4
ANIMAL_RUNNING_DURATION_DEFAULT = 10
ANIMAL_SLEEPING_DURATION_DEFAULT = 8
ANIMAL_ENERGY_LOSS_PER_MOVE_DEFAULT = 0

HARE_EATING_DURATION = 4
HARE_RUNNING_DURATION = 20
HARE_SLEEPING_DURATION = 10
HARE_MAX_SPEED = 20
HARE_MIN_REPRODUCE_DIST = 20
HARE_SEXUAL_AROUSAL = .69
HARE_FOOD_FINDING_PROBABILITY = .25
HARE_FOOD_PORTION = 50
HARE_VISUAL_ACUITY = 100
HARE_ENERGY_LOSS_PER_MOVE = 1

WOLF_EATING_DURATION = 2
WOLF_RUNNING_DURATION = 8
WOLF_SLEEPING_DURATION = 10
WOLF_MAX_SPEED = 15
WOLF_MIN_REPRODUCE_DIST = 20
WOLF_SEXUAL_AROUSAL = .31
WOLF_HUNT_PROBABILITY = .98
WOLF_HUNT_MIN_DIST = 30
WOLF_VISUAL_ACUITY = 80
WOLF_ENERGY_LOSS_PER_MOVE = 6