import random

ENV_RUNNING_TIME = 10000
SCREEN_LENGTH = 300
SCREEN_HEIGHT = 300

REPORT_INTERVAL = 5
NUM_OF_HARES = 5
NUM_OF_WOLVES = 3

ANIMAL_START_ENERGY = 1000
ANIMAL_MAX_SPEED_DEFAULT = 12
ANIMAL_EATING_DURATION_DEFAULT = 4
ANIMAL_RUNNING_DURATION_DEFAULT = 10
ANIMAL_SLEEPING_DURATION_DEFAULT = 8

HARE_EATING_DURATION = 4
HARE_RUNNING_DURATION = 20
HARE_SLEEPING_DURATION = 10
HARE_MAX_SPEED = 20
HARE_MIN_REPRODUCE_DIST = 20
HARE_SEXUAL_AROUSAL = .2
HARE_FOOD_FINDING_PROBABILITY = .2
HARE_FOOD_PORTION = 50

WOLF_EATING_DURATION = 2
WOLF_RUNNING_DURATION = 8
WOLF_SLEEPING_DURATION = 10
WOLF_MAX_SPEED = 15
WOLF_MIN_REPRODUCE_DIST = 20
WOLF_SEXUAL_AROUSAL = .2
WOLF_HUNT_PROBABILITY = .3
WOLF_HUNT_MIN_DIST = 30


def rand_x():
    return random.random() * SCREEN_LENGTH


def rand_y():
    return random.random() * SCREEN_HEIGHT