import random

ENV_RUNNING_TIME = 100000
SCREEN_LENGTH = 800
SCREEN_HEIGHT = 600

REPORT_INTERVAL = 5
NUM_OF_HARES = 100
NUM_OF_WOLVES = 40

ANIMAL_START_ENERGY = 10000
ANIMAL_MAX_SPEED_DEFAULT = 12
ANIMAL_EATING_DURATION_DEFAULT = 4
ANIMAL_RUNNING_DURATION_DEFAULT = 10
ANIMAL_SLEEPING_DURATION_DEFAULT = 8

HARE_EATING_DURATION = 4
HARE_RUNNING_DURATION = 20
HARE_SLEEPING_DURATION = 10
HARE_MAX_SPEED = 20

WOLF_EATING_DURATION = 2
WOLF_RUNNING_DURATION = 8
WOLF_SLEEPING_DURATION = 10
WOLF_MAX_SPEED = 10
WOLF_HUNT_PROBABILITY = 0.6


def rand_x():
    return random.random() * SCREEN_LENGTH


def rand_y():
    return random.random() * SCREEN_HEIGHT